version: '3.8'

volumes:
  postgres_data:
    driver: local

services:

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/postgres/scripts/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      POSTGRES_USER: serendipity
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: serendipity

  pgadmin:
    image: dpage/pgadmin4:6.1
    restart: always
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - .:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@serendipity.org.au}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-secret}

  serendipity-identity-server:
    # uncomment the following line to use the project's Docker Hub image
    # image: robinyo/serendipity-identity-server:latest
    image: serendipity-identity-server:latest
    container_name: serendipity-identity-server
    build:
      context: ./services/identity-service
      dockerfile: Dockerfile
    ports:
      - "30002:8080"
    volumes:
      - .:/export
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      KEYCLOAK_FRONTEND_URL: http://127.0.0.1:30002/auth
      KEYCLOAK_IMPORT: /tmp/development-realm.json
      KEYCLOAK_MIGRATION_STRATEGY: OVERWRITE_EXISTING
      DB_VENDOR: POSTGRES
      # DB_ADDR: postgres
      DB_ADDR: host.docker.internal
      DB_USER: serendipity
      DB_PASSWORD: secret
      DB_DATABASE: serendipity
      # DB_SCHEMA: public
      # See: /services/postgres/scripts/create_schema.sql
      DB_SCHEMA: keycloak
    depends_on:
      - postgres

  serendipity-party-service:
    # uncomment the following line to use the project's Docker Hub image
    # image: robinyo/serendipity-party-service:latest
    image: serendipity-party-service:latest
    container_name: serendipity-party-service
    build:
      context: ./modules/party-service
      dockerfile: Dockerfile
    ports:
      - "30101:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/serendipity
    depends_on:
      - postgres

  serendipity-work-service:
    # uncomment the following line to use the project's Docker Hub image
    # image: robinyo/serendipity-work-service:latest
    image: serendipity-work-service:latest
    container_name: serendipity-work-service
    build:
      context: ./modules/work-service
      dockerfile: Dockerfile
    ports:
      - "30102:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/serendipity
    depends_on:
      - postgres

  serendipity:
    # uncomment the following line to use the project's Docker Hub image
    # image: robinyo/serendipity:latest
    image: serendipity:latest
    container_name: serendipity
    build:
      context: ./modules/web-bff
      dockerfile: Dockerfile
    ports:
      - "30001:8080"
    env_file: ./modules/web-bff/web-bff.env
    depends_on:
      - serendipity-identity-server
