version: '3.8'

services:

  postgres:
    container_name: postgres
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    env_file: ./services/postgres/postgres.env

  pgadmin:
    container_name: pgadmin
    build:
      context: ./services/pgadmin
      dockerfile: Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@serendipity.org.au}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-secret}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - .:/root/.pgadmin

  serendipity-identity-server:
    container_name: serendipity-identity-server
    # image: robinyo/serendipity-identity-server:latest
    image: serendipity-identity-server:latest
    build:
      context: ./services/identity-service
      dockerfile: Dockerfile
    ports:
      - "30002:8080"
    # volumes:
    #   - .:/export
    env_file: ./services/identity-service/identity-service.env

  serendipity-party-service:
    container_name: serendipity-party-service
    # image: robinyo/serendipity-party-service:latest
    image: serendipity-party-service:latest
    build:
      context: ./modules/party-service
      dockerfile: Dockerfile
    ports:
      - "30101:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/serendipity
    depends_on:
      - postgres

  serendipity-work-service:
    container_name: serendipity-work-service
    # image: robinyo/serendipity-work-service:latest
    image: serendipity-work-service:latest
    build:
      context: ./modules/work-service
      dockerfile: Dockerfile
    ports:
      - "30102:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/serendipity
    depends_on:
      - postgres

  serendipity:
    container_name: serendipity
    # image: robinyo/serendipity:latest
    image: serendipity:latest
    build:
      context: ./modules/web-bff
      dockerfile: Dockerfile
    ports:
      - "30001:8080"
    env_file: ./modules/web-bff/web-bff.env
    depends_on:
      - serendipity-identity-server
