apiVersion: v1
kind: Service
metadata:
  labels:
    app: serendipity
  name: serendipity-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 8080
      protocol: TCP
  selector:
    app: serendipity
