apiVersion: v1
data:
  DB_VENDOR: h2
  KEYCLOAK_FRONTEND_URL: http://127.0.0.1:30002/auth
  KEYCLOAK_IMPORT: /tmp/development-realm.json
  KEYCLOAK_MIGRATION_STRATEGY: OVERWRITE_EXISTING
  KEYCLOAK_PASSWORD: secret
  KEYCLOAK_USER: admin
kind: ConfigMap
metadata:
  name: serendipity-identity-server-configmap
  namespace: default
