apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: serendipity-identity-server
  name: serendipity-identity-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serendipity-identity-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: serendipity-identity-server
    spec:
      containers:
        - name: serendipity-identity-server
          image: robinyo/serendipity-identity-server:0.0.1.Beta3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: serendipity-identity-server-configmap
