apiVersion: v1
data:
  AUTHORIZATION_URI: http://127.0.0.1:30002/auth/realms/development/protocol/openid-connect/auth
  CLIENT_ID: serendipity-web-bff
  CLIENT_SECRET: 1daa2667-d208-49a4-ad81-5b94746ba88f
  JWK_SET_URI: http://127.0.0.1:30002/auth/realms/development/protocol/openid-connect/certs
  LOGOUT_URI: http://127.0.0.1:30002/auth/realms/development/protocol/openid-connect/logout
  SCOPE: openid,profile,email,address,phone
  TOKEN_URI: http://127.0.0.1:30002/auth/realms/development/protocol/openid-connect/token
  USER_INFO_URI: http://127.0.0.1:30002/auth/realms/development/protocol/openid-connect/userinfo
kind: ConfigMap
metadata:
  name: serendipity-configmap
  namespace: default
