apiVersion: v1
kind: Service
metadata:
  labels:
    app: serendipity-identity-server
  name: serendipity-identity-server-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30002
      targetPort: 8080
      protocol: TCP
  selector:
    app: serendipity-identity-server
