server:
  port: 8080

logging:
  level:
    root: INFO
    org.flowable: INFO
    org.hibernate.SQL: WARN
    org.springframework.web: INFO
    reactor.netty.http.client.HttpClient: INFO

spring:
  datasource:
    username: serendipity
    password: secret
  main:
    banner-mode: off
  profiles:
    active: @spring.profiles.active@

# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:10001/auth/realms/development/protocol/openid-connect/certs



# spring.jpa.properties.hibernate.order_by.default_null_ordering=last

# https://docs.spring.io/spring-security/site/docs/5.2.12.RELEASE/reference/html/oauth2.html#oauth2login-boot-property-mappings
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
# https://github.com/spring-projects/spring-security-samples/blob/main/servlet/spring-boot/java/oauth2/login/src/main/resources/application.yml
